x-build-common: &build-common
  context: .
  dockerfile: Dockerfile

x-environment-common: &environment-common
  HOST_UID: ${HOST_UID:-1000}
  HOST_GID: ${HOST_GID:-1000}

x-service-common: &service-common
  environment:
    <<: *environment-common

  volumes:
    - ./workdir:/workdir

  working_dir: /workdir
  stdin_open: true
  tty: true
  network_mode: host

services:

  cppdev:
    <<: *service-common

    build:
      <<: *build-common
      target: cppdev

    image: i_cppdev
    container_name: c_cppdev


  strictdoc_cppdev:
    <<: *service-common

    build:
      <<: *build-common
      target: strictdoc_cppdev

    image: i_strictdoc_cppdev
    container_name: c_strictdoc_cppdev

  codex_strictdoc_cppdev:
    <<: *service-common

    build:
      <<: *build-common
      target: codex_strictdoc_cppdev

    image: i_codex_strictdoc_cppdev
    container_name: c_codex_strictdoc_cppdev

    environment:
      <<: *environment-common
      CODEX_HOME: /codex

    volumes:
      - ./workdir:/workdir
      - ${HOME}/.codex-strictdoc:/codex
